name: final_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http:
  provider:
  android_id:
  device_info_plus:
  flutter_launcher_icons:
  flutter_native_splash:
  shared_preferences:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app_icon.png"

flutter_native_splash:
  color: "#000000" # Background color for the splash screen
  image: "assets/images/splash_logo.png" # Path to your splash screen logo
  android: true
  ios: true

fonts:
  - family: Montserrat
    fonts:
      - asset: assets/fonts/Montserrat-Regular.ttf
      - asset: assets/fonts/Montserrat-Bold.ttf
        weight: 700
      - asset: assets/fonts/Montserrat-Light.ttf
        weight: 300
      - asset: assets/fonts/Montserrat-Thin.ttf
        weight: 100
      - asset: assets/fonts/Montserrat-Medium.ttf
        weight: 500
